export const LIST_FORCHAT_REQUEST = 'LIST_FORCHAT_REQUEST';
export const LIST_FORCHAT_SUCCESS = 'LIST_FORCHAT_SUCCESS';
export const LIST_FORCHAT_FAIL = 'LIST_FORCHAT_FAIL';


export const SINGLE_TEXT_REQUEST = 'SINGLE_TEXT_REQUEST';
export const SINGLE_TEXT_SUCCESS = 'SINGLE_TEXT_SUCCESS';
export const SINGLE_TEXT_FAIL = 'SINGLE_TEXT_FAIL';


export const POP_NOTIFICATION = 'POP_NOTIFICATION';
export const UN_POP_NOTIFICATION = 'UN_POP_NOTIFICATION';
