export const PROFILE_PIC_UPLOAD_REQUEST = 'PROFILE_PIC_UPLOAD_REQUEST';
export const PROFILE_PIC_UPLOAD_SUCCESS = 'PROFILE_PIC_UPLOAD_SUCCESS';
export const PROFILE_PIC_UPLOAD_FAIL = 'PROFILE_PIC_UPLOAD_FAIL';



export const PROFILE_PIC_DELETE_REQUEST = 'PROFILE_PIC_DELETE_REQUEST';
export const PROFILE_PIC_DELETE_SUCCESS = 'PROFILE_PIC_DELETE_SUCCESS';
export const PROFILE_PIC_DELETE_FAIL = 'PROFILE_PIC_DELETE_SUCCESS';
export const PROFILE_PIC_DELETE_RESET = 'PROFILE_PIC_DELETE_RESET';

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

