export const LIKE_REQUEST = 'LIKE_REQUEST';
export const LIKE_SUCCESS = 'LIKE_SUCCESS';
export const LIKE_FAIL = 'LIKE_FAIL';
export const LIKE_RESET = 'LIKE_RESET';


export const COMMENT_REQUEST = 'COMMENT_REQUEST';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';
export const COMMENT_FAIL = 'COMMENT_FAIL';
export const COMMENT_RESET = 'COMMENT_RESET';


export const EDIT_CAPTION_REQUEST = 'EDIT_CAPTION_REQUEST';
export const EDIT_CAPTION_SUCCESS = 'EDIT_CAPTION_SUCCESS';
export const EDIT_CAPTION_FAIL = 'EDIT_CAPTION_FAIL';


export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';


export const GET_LIKES_REQUEST = 'GET_LIKES_REQUEST';
export const GET_LIKES_SUCCESS = 'GET_LIKES_SUCCESS';
export const GET_LIKES_FAIL = 'GET_LIKES_FAIL';
export const GET_LIKES_RESET = 'GET_LIKES_RESET';


export const NOTIFICATION_REQUEST = 'NOTIFICATION_REQUEST';
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';
export const NOTIFICATION_FAIL = 'NOTIFICATION_FAIL';
export const NOTIFICATION_RESET = 'NOTIFICATION_RESET';